### ISSUE TITLE
Parsing nested json in returned json objects

### ISSUE THREAD

**Issue by revansSZ** [frikky/Shuffle#129]
Hi,

I was wondering if you could provide guidance on parsing nested json. The behavior is strange in how the data is pulled. In my case I have the sample json.

//sample data, there is an array of json events, each with varying levels of nested json blocks.
{
	"data" {
	0: {
	"event_type": "something",
	"computer": {
		"hostname": "lappytoppy",
		"external_ip": "1.1.1.1"
		"network_addresses": {
		0: {
		"mac": "xx:xx:xx:xx:xx"
		}
	}
	}
	}
	}
}
I call this in a "repeat back to me" app for testing from the prior api call. 
{
"hostnames": $Cisco_AMP_Events.data.#.computer.hostname
}

Normally I'd expect this to Look at the data KV, which contains an array of events, each have a nested json structure, such as computer, which then contains hostname and other values. 

When I use the above, it instead returns the entire json object at $Cisco_AMP_Events.data.#.computer. It doesn't appear to store the nested values.

This seems to follow the instruction guide, but the logic seems to break for nested objects. I may be missing something on my end however.

Thanks!

**Comment by revansSZ** [comment]
I think this might be somewhat of the same issue seen in Issue #78 regarding: You can't go deeper than one level (#.data.#)

**Comment by frikky** [comment]
Heyo! This doesnt look to be valid JSON, as keys in JSON needs to be a string, not 0 or 1 or similar. It looks like a valid javascript object tho.

You're right that there's a looping issue, but nesting should work. Here's what ill do later (on my phone rn 😉):
1. Show you how this JSON can be built and used
2. Create an issue to add a warning for things that "look like" JSON, but in reality aren't. Maybe add a fixer too.

I'll get back to this

**Comment by revansSZ** [comment]
Hi Frikky,

You are right about that, the notation seen above is as reported by the Shuffle UI when an API call is completed. I'm assuming this is the "display notation".

The actual returned data is in json format.  Here is a sample from Cisco AMPs API documentation.  

{
  "version": "v1.2.0",
  "metadata": {
    "links": {
      "self": "https://api.amp.cisco.com/v1/events?limit=2",
      "next": "https://api.amp.cisco.com/v1/events?limit=2&offset=2"
    },
    "results": {
      "total": 1252,
      "current_item_count": 2,
      "index": 0,
      "items_per_page": 2
    }
  },
  "data": [
    {
      "id": 6180352115244794000,
      "timestamp": 1582222838,
      "timestamp_nanoseconds": 279000000,
      "date": "2020-02-20T18:20:38+00:00",
      "event_type": "Threat Detected",
      "event_type_id": 1090519054,
      "detection": "W32.GenericKD:ZVETJ.18gs.1201",
      "detection_id": "6180352115244793858",
      "connector_guid": "20a0ce9f-44d1-4cbb-ab04-8a0705448b72",
      "group_guids": [
        "6c3c2005-4c74-4ba7-8dbb-c4d5b6bafe03"
      ],
      "severity": "Medium",
      "computer": {
        "connector_guid": "20a0ce9f-44d1-4cbb-ab04-8a0705448b72",
        "hostname": "Demo_Upatre",
        "external_ip": "69.226.122.127",
        "user": "A@TEMPLATE-W7X86",
        "active": true,
        "network_addresses": [
          {
            "ip": "230.122.135.241",
            "mac": "3f:1e:b2:28:25:24"
          }
        ],
        "links": {
          "computer": "https://api.amp.cisco.com/v1/computers/20a0ce9f-44d1-4cbb-ab04-8a0705448b72",
          "trajectory": "https://api.amp.cisco.com/v1/computers/20a0ce9f-44d1-4cbb-ab04-8a0705448b72/trajectory",
          "group": "https://api.amp.cisco.com/v1/groups/6c3c2005-4c74-4ba7-8dbb-c4d5b6bafe03"
        }
      },
      "file": {
        "disposition": "Malicious",
        "file_name": "wsymqyv90.exe",
        "file_path": "\\\\?\\C:\\Users\\Administrator\\AppData\\Local\\Temp\\OUTLOOK_TEMP\\wsymqyv90.exe",
        "identity": {
          "sha256": "b630e72639cc7340620adb0cfc26332ec52fe8867b769695f2d25718d68b1b40",
          "sha1": "70aef829bec17195e6c8ec0e6cba0ed39f97ba48",
          "md5": "e2f5dcd966e26d54329e8d79c7201652"
        },
        "parent": {
          "process_id": 4040,
          "disposition": "Clean",
          "file_name": "iexplore.exe",
          "identity": {
            "sha256": "b4e5c2775de098946b4e11aba138b89d42b88c1dbd4d5ec879ef6919bf018132",
            "sha1": "8de30174cebc8732f1ba961e7d93fe5549495a80",
            "md5": "b3581f426dc500a51091cdd5bacf0454"
          }
        }
      }
    },
    {
      "id": 6180351977805840000,
      "timestamp": 1582222806,
      "timestamp_nanoseconds": 548000000,
      "date": "2020-02-20T18:20:06+00:00",
      "event_type": "Threat Detected",
      "event_type_id": 1090519054,
      "detection": "W32.GenericKD:ZVETJ.18gs.1201",
      "detection_id": "6180351977805840385",
      "connector_guid": "20a0ce9f-44d1-4cbb-ab04-8a0705448b72",
      "group_guids": [
        "6c3c2005-4c74-4ba7-8dbb-c4d5b6bafe03"
      ],
      "severity": "Medium",
      "computer": {
        "connector_guid": "20a0ce9f-44d1-4cbb-ab04-8a0705448b72",
        "hostname": "Demo_Upatre",
        "external_ip": "69.226.122.127",
        "user": "A@TEMPLATE-W7X86",
        "active": true,
        "network_addresses": [
          {
            "ip": "230.122.135.241",
            "mac": "3f:1e:b2:28:25:24"
          }
        ],
        "links": {
          "computer": "https://api.amp.cisco.com/v1/computers/20a0ce9f-44d1-4cbb-ab04-8a0705448b72",
          "trajectory": "https://api.amp.cisco.com/v1/computers/20a0ce9f-44d1-4cbb-ab04-8a0705448b72/trajectory",
          "group": "https://api.amp.cisco.com/v1/groups/6c3c2005-4c74-4ba7-8dbb-c4d5b6bafe03"
        }
      },
      "file": {
        "disposition": "Malicious",
        "file_name": "wsymqyv90.exe",
        "file_path": "\\\\?\\C:\\Users\\Administrator\\AppData\\Local\\Temp\\OUTLOOK_TEMP\\wsymqyv90.exe",
        "identity": {
          "sha256": "b630e72639cc7340620adb0cfc26332ec52fe8867b769695f2d25718d68b1b40",
          "sha1": "70aef829bec17195e6c8ec0e6cba0ed39f97ba48",
          "md5": "e2f5dcd966e26d54329e8d79c7201652"
        },
        "parent": {
          "process_id": 4040,
          "disposition": "Clean",
          "file_name": "iexplore.exe",
          "identity": {
            "sha256": "b4e5c2775de098946b4e11aba138b89d42b88c1dbd4d5ec879ef6919bf018132",
            "sha1": "8de30174cebc8732f1ba961e7d93fe5549495a80",
            "md5": "b3581f426dc500a51091cdd5bacf0454"
          }
        }
      }
    }
  ]
}

https://api-docs.amp.cisco.com/api_actions/details?api_action=GET+%2Fv1%2Fevents&api_host=api.amp.cisco.com&api_resource=Event&api_version=v1


Essentially the data key contains an array of json objects, one per "event" in the events api.

I'm roughly trying to do the following (for this app as an example, and for others):
1) Make some api call for list of events
2) For each event returned, evaluate some data
3) Based on the evaluation of above data, take some action, or no action.
4) Repeat per returned object in array. 

If I call get events for this api, and it returns 10 events, if the event is "AllYourBaseAreBelongToUS" and disposition is "Malicious", then execute the next app with just that objects data. Then evaluate the next.

I see the above is the most common use case for Shuffle, but the ideas are limitless.

I appreciate your help!!

**Comment by frikky** [comment]
First of, the JSON you shared - there's an issue with it in all linters I've tested on the following line(s):

![image](https://user-images.githubusercontent.com/5719530/92203863-80a9eb00-ee82-11ea-8a1d-1fd163bd8647.png)

This is a solvable issue, since all backslashes can be replaced with double ones. [I created an issue for it](https://github.com/frikky/Shuffle/issues/131), but it might take some time to get to, so I'm seeing it as a bug with Cisco's API and filepaths in general for now.

Secondly - what you said is absolutely one of the primary reasons Shuffle is being built in the first place. The first reason was actually for real-time data (one event at a time with webhooks etc), but it became clear pretty fast that looping is necessary (with schedules etc). The reason we haven't moved into default workflow creation and sharing yet, is because we still haven't moved out of our "infancy" stage when it comes to for-loops. [Here's more on current issues of for loops that we will solve ASAP](https://github.com/frikky/Shuffle/issues/104). PS: Part of the reason we kept the # rather than for-loops so far is because it's way more efficient architecture-wise. 

Anyway, [here's a workflow with your data](https://github.com/frikky/shuffle-workflows/blob/master/129_testing.json) that should work when the App SDK is updated to handle loops properly. Try importing and running it, and you'll see that it can do loops, but the conditional checks don't work properly yet.

**Comment by frikky** [comment]
Btw: I'll get on fixing the SDK after the weekend. I've been waiting for people to get to these kind of issues (actual implementations), before spending too much time on them.

**Comment by frikky** [comment]
Hey! 

Since we don't have a really good way of handling for-loops yet, I ended up creating a workaround with an app until we do (this is part of the beauty of Shuffle tbh):

![image](https://user-images.githubusercontent.com/5719530/92407221-3eaace80-f13a-11ea-8652-5624d9db4d1d.png)

What it does:
1. "Cisco data" contains the data you have (which will be an API call). Data length: 2. App: Shuffle Testing (printing)
2. "Filter cisco data" takes the list ($cisco_data.data) and filters based on the field "detection = W32.GenericKD:ZVETJ.18gs.1201". This is another way to have conditions. Data length: 1. App: Shuffle Tools
3.  Loop through results from "Filter cisco data" to create cases in TheHive

Now, say you want to e.g. get data from Elasticsearch, I'd do something like this:
1. Make sure your search in ELK works
2. Use a condition to check if there are any results (branch)
3. Use Shuffle-tools to loop and filter data
4. Do something with the filtered results
5. Add a schedule to do this every X seconds/minutes/hours/days etc.

Tell me more about your use-cases and I'll help out more :+1:

**Comment by frikky** [comment]
This is now properly fixed! Update the App SDK, then force update the apps.

1. docker pull frikky/shuffle:app_sdk
2. Click /apps -> top right -> force update

**Comment by frikky** [comment]
Closing as we haven't talked about this in a while. Let's bring it back up in our meeting if it can't be resolved.
