### ISSUE TITLE
Add proxy option for Apps

### ISSUE THREAD

**Issue by lucyel** [frikky/Shuffle#189]
The apps that needed to connect to the internet to call api or do stuff need to be able to have proxy option to connect to internet.
It can be either in the docker-compose file or inside the app action themselve (for each action).

**Comment by 8ear** [comment]
Is already done in /docker-compose.yml or I am wrong?

**Comment by frikky** [comment]
Hey @8ear - it's proxy in Docker-compose is just for the backend. The apps are individual containers and should be configured from the frontend. We'll make it a configuration.

**Comment by frikky** [comment]
Should definitely have this for 1.0.0. Will probably be configured through Orborus, or even within the container authentication itself.

**Comment by frikky** [comment]
Hey @8ear and @lucyel - I implemented a temporary version of this at the host level. We'll have to make it at the app level later on, but this should help out for now.

In the Orborus docker-compose, these environments now exist. The proxy settings are obvious (HTTP/HTTPS), while the latter two options are a bit obscure:

SHUFFLE_PASS_WORKER_PROXY means if you want to use the same proxy as Orborus for the worker. Default true, since Orborus and Worker use them same access to the backend, while Apps won't.
SHUFFLE_PASS_APP_PROXY means if you want to pass the same proxy as Orborus to your APPS. Default false, since you may not want to have all apps go through the same proxy.

docker-compose.yml:
```
      - HTTP_PROXY=${SHUFFLE_HTTP_PROXY}
      - HTTPS_PROXY=${SHUFFLE_HTTPS_PROXY}
      - SHUFFLE_PASS_WORKER_PROXY=${SHUFFLE_PASS_WORKER_PROXY}
      - SHUFFLE_PASS_APP_PROXY=${SHUFFLE_PASS_APP_PROXY}
```

.env:
```
SHUFFLE_HTTP_PROXY=http://your-proxy
SHUFFLE_HTTPS_PROXY=https://your-proxy
SHUFFLE_PASS_WORKER_PROXY=TRUE
SHUFFLE_PASS_APP_PROXY=TRUE
```

PS: This requires 0.8.76 of Orborus and the Worker. Whether you have them already or not run this:
```
docker pull ghcr.io/frikky/orborus:0.8.76
docker pull ghcr.io/frikky/worker:0.8.76
```

Please test and get back to me :)

**Comment by frikky** [comment]
Closing as there hasn't been any activity. If you find an issue, please get back to me. we'll surely add this to the UI for OpenAPI apps in the future :)
