### ISSUE TITLE
Cannot create condition from webhook

### ISSUE THREAD

**Issue by dadokkio** [frikky/Shuffle#206]
**Describe the bug**
The line exiting from a webhook cannot be selected for condition

**To Reproduce**
Add a webhook and another node
Collect them
Select the line, nothing happen

**Expected behavior**
Possibility to had condition on line exiting from webhook

**Comment by frikky** [comment]
oh, haven't thought of this one.

**Comment by frikky** [comment]
Hey again! This is now kind of fixed, with one caveat. Because of how the branch system is made, it doesn't check it's coming from. This means that even if you run a workflow manually, the condition from a trigger will be check. 

E.g. in the picture below, it checks if $exec == false. This should in an ideal world work based on where it comes from (only webhook in this case), but it will be checked even if you click the "play" button. 

I won't fix this issue right now, as it will require loads of debugging with source/destinations of branches, but this will make conditions from webhooks and other triggers work :+1: It shouldn't break anything either, as these branches didn't exist before :)

![image](https://user-images.githubusercontent.com/5719530/101617335-cd1c3e00-3a10-11eb-95d5-9cd774a7b940.png)
