### ISSUE TITLE
Images not built on App run

### ISSUE THREAD

**Issue by pooki3bear** [frikky/Shuffle#212]
**Is your feature request related to a problem? Please describe.**
If you delete a local shuffle image, the image is not rebuilt when the app is run.

**Describe the solution you'd like**
Shuffle should check if an image is available when an app launches, and build or pull as appropriate. "BUILDING" status would be added to nodes if this causes delay.

**Describe alternatives you've considered**
I manually build by forcing a pull to my fork, which is non-optimal #211 

**Additional context**

**Comment by frikky** [comment]
This is a known issue, and related to #161 

I like your solution, showing "BUILDING" status to the user. I believe this feature would be way better though, if there was a common location to validate it with. E.g. when do you choose to force update apps to get this working if there's a local repository for the same apps? We have hash checks and such, but this isn't that trivial.

What I'm thinking, which is why it hasn't been touched:
1. Shuffle will make a location remotely that is "ground truth". This will basically be a search engine for apps (and other things). If an app doesn't exist -> go look for it.
2. You can add your own repos that it also validates with, which will have priority. Probably won't talk to remote github repos, but rather use a local copy, otherwise it would be a lot of resources to spend per workflow ran.

**Comment by pooki3bear** [comment]
Now that automated builds are in place for app images, it might make sense to have priority of:
1 - pull app:latest
2 - If pulling from custom repo, look for tagged images (maybe unrealistic)
3 - If pulling from custom repo build images locally
