### ISSUE TITLE
Hello world not finishing

### ISSUE THREAD

**Issue by kissmywhat** [frikky/Shuffle#47]
As requested, in https://medium.com/security-operation-capybara/getting-started-with-shuffle-an-open-source-soar-platform-part-2-1d7c67a64244

I've got Centos8 in a VM, all working up to the point of running the test app with hello world.  It says Executing Workflow, status is executing, started timestamp looks ok and the ID is a nice long UUID type string, the actions section just has spinning red circles.

**Comment by frikky** [comment]
Hey! There's a couple of different reasons this might happen, but I'll need some more information.

Can you try to execute the workflow again and then type this in your terminal:
```
docker ps
```

I'm looking for whether the worker for the workflow is executing at all.

**Comment by timoles** [comment]
I had a similar problem yesterday (and forgot to open an issue about it). In my case I had a too new version of docker installed. 
Docker changed their EngineAPI to 1.40 [recently](https://docs.docker.com/engine/api/version-history/). When checking the orborus docker logs:

```bash
docker ps
# -> get the container ID of the "shuffle-orborus" image.
docker logs <orborus-image-id>
```

There it repeatetly displayed an error message "API version incompatible with 1.39" (or similar). Downgrading docker helped with the issue. A `docker --version` displays `19.03.11` for me.

**Comment by kissmywhat** [comment]
docker ps isn't showing anything extra running when the workflow is supposed to be executing.
I'm getting the same API issue timoles reported in the orborus image, docker --version shows 19.03.11 build 42e35e61f3

Happy to swap out docker versions or change to a different Linux if that will help (it's a brand new VM), just need a suggestion on where to go.

**Comment by timoles** [comment]
Sadly I haven't gotten the exact commands right now, but at first I uninstalled docker completely (it was installed on Ubuntu through "snap", so a `snap remove docker` did it for me)

After you uninstalled docker you should be good to go by following [this writeup](https://medium.com/@gauravsj9/how-to-install-specific-docker-version-on-linux-machine-d0ec2d4095).\
On Ubuntu the step `sudo apt-get install docker-ce=17.06.0~ce-0~ubuntu` is important (and out of date), here you want to install something like `sudo apt-get install docker-ce=19.03.11~ce-0~ubuntu`  (or similar, this command might not be exactly correct)

This is a rough waymark, you can also google something like "<your-linux-distro>" install specific docker version". That should lead you the right way in order to be able to install docker 19.03.11. (Note: you have the same docker version as I installed, but I _think_ you have a to new version of `docker-ce` (the one which uses 1.40))

**Comment by frikky** [comment]
Ah, I had no idea this was an issue still. There shouldn't be a reason to have 1.40 exactly, but that's just what was defined because of a previous issue.

![image](https://user-images.githubusercontent.com/5719530/83737616-8a3d7000-a653-11ea-912f-e073f7e446da.png)

1. Change this line in your docker-compose to the API version you have (see above) https://github.com/frikky/Shuffle/blob/master/docker-compose.yml#L60
2. Restart docker-compose:
```
docker-compose down
docker-compose up
```

I'm not sure how to work around this issue completely yet, but it either has to be a part of the installation guide or I have to create a bash script that plots it in there automatically. I'll add it to the installation guide for now.

**Comment by kissmywhat** [comment]
Thanks, that worked, hello world is now completing as expected.

**Comment by frikky** [comment]
Great to hear! Added info to the install guide in case (when) others hit the same issue.
