### ISSUE TITLE
No data is returned when the app has a large amount of data

### ISSUE THREAD

**Issue by 219liangyi** [frikky/Shuffle#641]
**Describe the bug**

![image](https://user-images.githubusercontent.com/19781251/147534801-e99e53e1-949d-4043-a347-677eb9bb278c.png)

I made an app, and the back-end returned the base64 encoded image. When my image was large, the back-end returned empty. Is there a way to solve this?

**Comment by frikky** [comment]
> **Describe the bug**
> 
> ![image](https://user-images.githubusercontent.com/19781251/147534801-e99e53e1-949d-4043-a347-677eb9bb278c.png)
> 
> I made an app, and the back-end returned the base64 encoded image. When my image was large, the back-end returned empty. Is there a way to solve this?

Could you show exactly what information doesn't work? There's a lot to how data is being managed on the backend, and any help with replication helps a lot.  

Best case: make a workflow and paste in the base64 to replicate it. Also: in some cases, apps don't return anything because the API's don't return anything either.

**Comment by 219liangyi** [comment]
我已经解决了它

**Comment by frikky** [comment]
> 我已经解决了它

ヤッタ!

(Sorry, I just speak Japanese, not Chinese yet)
