### ISSUE TITLE
Backend server gives error while starting go run command

### ISSUE THREAD

**Issue by kp625544** [frikky/Shuffle#7]
Hello,
I ran the following command while following the installation guide
`go run *.go`
 and encountered the following error:
`2020/05/21 09:20:51 Running INIT process
2020/05/21 09:20:51 DBclient error during init: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
exit status 1`
![Screenshot 2020-05-21 at 2 51 38 PM](https://user-images.githubusercontent.com/18206620/82544588-f6f43d00-9b72-11ea-9418-da718ad634a6.png)

**Comment by frikky** [comment]
Hey! This is due to the fact that it was a 100% cloud service 1,5 weeks ago, and I didn't get around to fix the database, which is still a Google cloud database.

Do one of the following:
1. Set environment variable GOOGLE_APPLICATION_CREDENTIALS to point to a valid Google cloud config (as the error says)
2. Change the main.go line with "log.Fatalf" to "log.Printf". 

It's a preliminary thing that only affects local environments it seems

**Comment by kp625544** [comment]
Thanks! So is GCP mandatory to install this? as I don't have that availability currently.

**Comment by frikky** [comment]
There's a workaround in the Docker container that enables skipping. Not 100% sure how it works

**Comment by frikky** [comment]
Closing as this is a non-issue until the database is changed
